---
- name: Install Node Exporter
  hosts: all
  become: yes
  tasks:
    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz

    - name: Ensure /opt directory exists
      file:
        path: /opt
        state: directory

    - name: Check if the tarball exists
      stat:
        path: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
      register: tarball_file

    - name: Debug tarball file
      debug:
        var: tarball_file

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes
      when: tarball_file.stat.exists

    - name: Check if node_exporter binary exists after extraction
      stat:
        path: /opt/node_exporter-1.6.1.linux-amd64/node_exporter
      register: node_exporter_binary

    - name: Debug node_exporter_binary
      debug:
        var: node_exporter_binary

    - name: Move Node Exporter binary to /usr/local/bin
      command: mv /opt/node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
      when: node_exporter_binary.stat.exists

    - name: Create Node Exporter service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /sbin/nologin

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
