---
- hosts: all
  become: yes
  tasks:
    - name: Download and unpack node exporter binary
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
        dest: "/tmp/"
        remote_src: yes
    - name: Create node exporter group
      group:
          name: "node_exporter"
          state: present
    - name: Create node exporter user
      user:
        name: "node_exporter"
        group: "node_exporter"
        state: present
    - name: Copy node exporter systemd unit file
      copy:
        src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
        dest: /usr/bin/
        mode: 0755
        remote_src: yes
          #mode: 0755
    - name: Creating a file with content
      copy:
          dest: "/etc/systemd/system/node_exporter.service"
          content: |
            [Unit]
              Description=Node Exporter
              Documentation=https://prometheus.io/docs/guides/node-exporter/
              Wants=network-online.target
              After=network-online.target

            [Service]
              User=node_exporter
              Group=node_exporter
              Type=simple
              Restart=on-failure
              ExecStart=/usr/bin/node_exporter --web.listen-address=:9101

            [Install]
              WantedBy=multi-user.target

    - name: Enable and start node exporter service
      systemd:
          daemon_reload: yes
          name: node_exporter
          enabled: yes
          state: started