---
- name: Install Node Exporter
  hosts: all
  become: yes
  tasks:
    - name: Download Node Exporter to control node
      delegate_to: localhost
      run_once: yes
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz

    - name: Copy Node Exporter tarball to client machines
      copy:
        src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz

    - name: Ensure /opt directory exists
      file:
        path: /opt
        state: directory

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Node Exporter binary to /usr/local/bin
      command: mv /opt/node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/node_exporter

    - name: Create Node Exporter service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /sbin/nologin

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
