---
- hosts: nexus
  become: yes
  tasks:
  - name: Download and unpack node exporter binary
    unarchive:
      src: wget "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
      dest: "/opt/"
      remote_src: yes
  - name: Create node exporter group
    group:
      name: "node_exporter"
      state: present

  - name: Create node exporter user
    user:
      name: "node_exporter"
      group: "node_exporter"
      state: present

  - name: Copy node exporter systemd unit file
    copy:
      src: ./node_exporter/node_exporter.service
      dest: /etc/systemd/system/
      mode: 0644

  - name: Enable and start node exporter service
    systemd:
      name: node_exporter
      enabled: yes
      state: started
