---
- name: Deploy Grafana
  hosts: kibana
  become: true

  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - gnupg2

    - name: Add Grafana repository
      yum_repository:
        name: grafana
        description: Grafana Repository
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: yes
        gpgkey: https://packages.grafana.com/gpg.key
        enabled: yes

    - name: Install Grafana
      package:
        name: grafana
        state: latest

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes

