apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-service
  labels:
    app: {{ .Release.Name }}-data-service
    chart: {{ template "deduplication.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.dataService.service.type }}
  ports:
    - port:  {{ .Values.dataService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.dataService.service.type "NodePort") (not (empty .Values.dataService.service.nodePort))) }}
      nodePort: {{ .Values.dataService.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-data-service
    release: {{ .Release.Name }}
