---
- name: Update /etc/hosts
  hosts: target_servers
  become: yes
  tasks:
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "10.0.92.30   SRV-WSO2-TEST-DEVQA-CONTROLPLANE01"
        - "10.0.92.31   SRV-WSO2-TEST-DEVQA-CONTROLPLANE02"
        - "10.0.92.27   dev-db01 dev-db01.local"
        - "10.0.92.28   dev-db02 dev-db02.local"
        - "10.0.92.29   dev-db03 dev-db03.local"
        - "127.0.0.1    localhost localhost.localdomain"

    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "10.0.92.30   SRV-WSO2-TEST-DEVQA-CONTROLPLANE01"
        - "10.0.92.31   SRV-WSO2-TEST-DEVQA-CONTROLPLANE02"
        - "10.0.92.27   dev-db01 dev-db01.local"
        - "10.0.92.28   dev-db02 dev-db02.local"
        - "10.0.92.29   dev-db03 dev-db03.local"
        - "127.0.0.1    localhost localhost.localdomain"
        
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "10.0.92.30   SRV-WSO2-TEST-DEVQA-CONTROLPLANE01"
        - "10.0.92.31   SRV-WSO2-TEST-DEVQA-CONTROLPLANE02"
        - "10.0.92.27   dev-db01 dev-db01.local"
        - "10.0.92.28   dev-db02 dev-db02.local"
        - "10.0.92.29   dev-db03 dev-db03.local"
        - "127.0.0.1    localhost localhost.localdomain"
