apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gs-secrets
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "gs.name" . }}
type: Opaque
data:
  databaseConnectionString: {{ include "db.connectionString" . | b64enc }}
  rabbitmqConnectionString: {{ include "rabbitmq.connectionString" . | b64enc }}
  redisConnectionString: {{ include "redis.connectionString" . | b64enc }}
  {{ if .Values.global.elasticsearch.user }}
  elasticsearchUser: {{ .Values.global.elasticsearch.user | b64enc }}
  {{ else }}
  elasticsearchUser: ""
  {{ end }}
  {{ if .Values.global.elasticsearch.password }}
  elasticsearchPassword: {{ .Values.global.elasticsearch.password | b64enc }}
  {{ else }}
  elasticsearchPassword: ""
  {{ end }}
