apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-single
  labels:
    app: {{ .Release.Name }}-worker-single
    chart: {{ template "gs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.workerSingle.replicaCount }}
{{- with .Values.workerSingle.strategy }}
  strategy:
{{ toYaml . | indent 4  }}
{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker-single
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        timestamp: {{ now | quote }}
      labels:
        app: {{ .Release.Name }}-worker-single
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: log4net-file
          configMap:
            name: {{ .Release.Name }}-logging-configmap
            items:
              - key: log4net.config
                path: log4net.config
{{ if .Values.workerSingle.nodeName }}
      nodeName: {{ .Values.workerSingle.nodeName }}
{{- end }}
{{ if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.image.pullSecrets | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.workerSingle.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: log4net-file
              mountPath: {{ .Values.log4Net.mountPath }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          env:
            - name: RabbitMQSettings__RabbitQueueName
              value: {{ .Values.global.rabbitmq.qname.singleInbox }}
            - name: RabbitMQSettings__QueuePriorityEnable
              value: '{{ .Values.global.rabbitmq.queuePriorityEnable }}'
            - name: RabbitMQSettings__ReplyRabbitQueueName
              value: {{ .Values.global.rabbitmq.qname.singleOutbox }}
            - name: Log4NetPath
              value: {{ .Values.log4Net.mountPath }}/log4net.config
            - name: IndexingContentLength
              value: "{{ .Values.global.indexingContentLength | int64  }}"
            - name: RequestTimeOut
              value: "{{ .Values.global.requestTimeOut | int64  }}"
            - name: IndexingCommandTimeout
              value: "{{ .Values.workerSingle.env.indexingCommandTimeout | int64 }}"
            - name: connectionStrings__RabbitMQ
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-gs-secrets
                  key: rabbitmqConnectionString
            - name: OnSiteClientSettings__ElasticSearchUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-global-config-map
                  key: es.url
            - name: elasticLogin
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-gs-secrets
                  key: elasticsearchUser
            - name: elasticPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-gs-secrets
                  key: elasticsearchPassword
            - name: TraceDebugInfo
              value: "{{ .Values.global.elasticsearch.traceDebugInfo }}"
{{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
{{- end }}
{{ if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
{{- end }}
          resources:
{{ toYaml .Values.workerSingle.resources | indent 12 }}
    {{- with .Values.workerSingle.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.workerSingle.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.workerSingle.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
