---
- name: Install Elasticsearch, Logstash, and Kibana
  hosts: jenkins_servers
  become: yes

  tasks:
    - name: Add Elastic GPG key
      rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository for Elasticsearch
      yum_repository:
        name: elasticsearch
        description: Elasticsearch Repository
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Elasticsearch
      yum:
        name: elasticsearch
        state: latest

    - name: Start and enable Elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Add Elastic repository for Logstash
      yum_repository:
        name: logstash
        description: Logstash Repository
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Logstash
      yum:
        name: logstash
        state: latest

    - name: Add Elastic repository for Kibana
      yum_repository:
        name: kibana
        description: Kibana Repository
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Kibana
      yum:
        name: kibana
        state: latest

    - name: Start and enable Kibana service
      service:
        name: kibana
        state: started
        enabled: yes

    - name: Allow incoming traffic on ports 9200 and 5601 (Elasticsearch and Kibana)
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 9200/tcp
        - 5601/tcp
