apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-api
  labels:
    app: {{ .Release.Name }}-web-api
    chart: {{ template "deduplication.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.webApi.replicaCount }}
{{- with .Values.webApi.strategy }}
  strategy:
{{ toYaml . | indent 4  }}
{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web-api
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}-web-api
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: log4net-file
          configMap:
            name: {{ .Release.Name }}-logging-configmap
            items:
              - key: log4net.config
                path: log4net.config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.webApi.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.webApi.image.pullPolicy }}
          volumeMounts:
            - name: log4net-file
              mountPath: {{ .Values.log4Net.mountPath }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: RabbitConfiguration__RabbitMQUri
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-deduplication-secrets
                  key: rabbitmqConnectionString
            - name: RabbitConfiguration__ConnectAttempts
              value: {{ .Values.global.rabbitmq.connectAttempts | quote }}
            - name: RabbitConfiguration__ReconnectInterval
              value: {{ .Values.global.rabbitmq.reconnectInterval }}
            - name: RabbitConfiguration__NetworkRecoveryInterval
              value: {{ .Values.global.rabbitmq.networkRecoveryInterval }}
            - name: RabbitPublisherConfiguration__QueueName
              value: {{ .Values.webApi.rabbitmq.publishQueueName }}
            - name: DataServiceRestConfiguration__DataServiceUri
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-global-config-map
                  key: dataServiceInternalUrl
            - name: ApplicationBasePath
              value: {{ .Values.webApi.ingress.path | trimPrefix "/" }}
            - name: Logger4NetConfiguration__LoggerName
              value: {{ .Values.log4Net.loggerName }}
            - name: Logger4NetConfiguration__LoggerRepositoryName
              value: {{ .Values.log4Net.repositoryName }}
            - name: Logger4NetConfiguration__LogFilePath
              value: {{ .Values.log4Net.filePath }}
            - name: MetricsOptions__Enabled
              value: {{ .Values.global.metrics.enabled | quote }}
            - name: MetricsOptions__GlobalTags__env
              value: {{ .Values.global.metrics.env }}
            - name: DuplicatesSearchConfiguration__DefaultMaxDuplicatesPerRecord
              value: {{ .Values.webApi.duplicateSearch.defaultMaxDuplicatesPerRecord | quote }}
          resources:
{{ toYaml .Values.webApi.resources | indent 12 }}
    {{- with .Values.webApi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.webApi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.webApi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
