apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-duplicates-search-worker
  labels:
    app: {{ .Release.Name }}-duplicates-search-worker
    chart: {{ template "deduplication.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.duplicatesSearchWorker.replicaCount }}
{{- with .Values.duplicatesSearchWorker.strategy }}
  strategy:
{{ toYaml . | indent 4  }}
{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-duplicates-search-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Release.Name }}-duplicates-search-worker
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: log4net-file
          configMap:
            name: {{ .Release.Name }}-logging-configmap
            items:
              - key: log4net.config
                path: log4net.config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.duplicatesSearchWorker.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.duplicatesSearchWorker.image.pullPolicy }}
          volumeMounts:
            - name: log4net-file
              mountPath: {{ .Values.log4Net.mountPath }}
          env:
            - name: RabbitConfiguration__RabbitMQUri
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-deduplication-secrets
                  key: rabbitmqConnectionString
            - name: RabbitConfiguration__QueueName
              value: {{ .Values.duplicatesSearchWorker.rabbitmq.consumerQueueName }}
            - name: RabbitConfiguration__ConnectAttempts
              value: {{ .Values.global.rabbitmq.connectAttempts | quote }}
            - name: RabbitConfiguration__ReconnectInterval
              value: {{ .Values.global.rabbitmq.reconnectInterval }}
            - name: RabbitConfiguration__NetworkRecoveryInterval
              value: {{ .Values.global.rabbitmq.networkRecoveryInterval }}
            - name: SearchWorkerElasticConfiguration__ElasticUri
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-deduplication-secrets
                  key: elasticsearchUri
            - name: SearchWorkerElasticConfiguration__DuplicateSearchPageSize
              value: {{ .Values.duplicatesSearchWorker.duplicateSearchPageSize | quote }}
            - name: SearchWorkerElasticConfiguration__MaxDuplicatesPerRecord
              value: {{ .Values.duplicatesSearchWorker.maxDuplicatesPerRecord | quote }}
            - name: SearchWorkerElasticConfiguration__MinimumShouldMatchPercentage
              value: {{ .Values.duplicatesSearchWorker.minimumShouldMatchPercentage | quote }}
            - name: DataServiceRestConfiguration__DataServiceUri
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-global-config-map
                  key: dataServiceInternalUrl
            - name: Logger4NetConfiguration__LoggerName
              value: {{ .Values.log4Net.loggerName }}
            - name: Logger4NetConfiguration__LoggerRepositoryName
              value: {{ .Values.log4Net.repositoryName }}
            - name: Logger4NetConfiguration__LogFilePath
              value: {{ .Values.log4Net.filePath }}
          resources:
{{ toYaml .Values.duplicatesSearchWorker.resources | indent 12 }}
    {{- with .Values.duplicatesSearchWorker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.duplicatesSearchWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.duplicatesSearchWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
