{{- if (include "security.shouldCreateSecret" .) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "security.secretName" . }}
type: Opaque
stringData:
  EncryptionCertificatePassword: "{{ .Values.Security.CertificatePassword }}"
{{- end }}