{{- if (include "auth.shouldCreateSecret" .) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "auth.secretName" . }}
type: Opaque
stringData:
  appSettings: |
    {
      "AuthToken": "{{ .Values.Auth.AuthToken }}"
    }
{{- end }}