kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-global-config-map
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "deduplication.name" . }}
data:
  {{- if .Values.global.dataServiceInternalUrl }}
  dataServiceInternalUrl: {{ .Values.global.dataServiceInternalUrl }}
  {{- else }}
  dataServiceInternalUrl: "http://{{ .Release.Name }}-data-service/api"
  {{- end }}
