kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-logging-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "deduplication.name" . }}
data:
  log4net.config: |
    <?xml version="1.0" encoding="utf-8"?>
    <log4net>
        <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
            <layout type="log4net.Layout.PatternLayout">
                <conversionPattern value="%date [%thread] %-5level: %message%newline" />
            </layout>
        </appender>
{{- if .Values.log4Net.grayLog.enabled }}
        <appender name="GelfAmqpAppender" type="Gelf4Net.Appender.GelfAmqpAppender, Gelf4Net.AmqpAppender">
            <remoteAddress value="{{ .Values.log4Net.grayLog.AMQP.host }}" />
            <remotePort value="{{ .Values.log4Net.grayLog.AMQP.port }}" />
            <username value="{{ .Values.log4Net.grayLog.AMQP.userName }}" />
            <password value="{{ .Values.log4Net.grayLog.AMQP.password }}" />
            <virtualHost value="{{ .Values.log4Net.grayLog.AMQP.virtualHost }}" />
            <exchange value="{{ .Values.log4Net.grayLog.AMQP.exchange }}" />
            <key value="{{ .Values.log4Net.grayLog.AMQP.routingKey }}" />
            <layout type="Gelf4Net.Layout.GelfLayout, Gelf4Net.Core">
                <param name="AdditionalFields" value="app:GelfAmqpAppender,version:1.0,Level:%level" />
                <param name="Facility" value="Deduplication" />
                <param name="IncludeLocationInformation" value="true" />
            </layout>
        </appender>
{{- end }}
        <root>
            <level value="{{ .Values.log4Net.level }}" />
            <appender-ref ref="ConsoleAppender" />
{{- if .Values.log4Net.grayLog.enabled }}
            <appender-ref ref="GelfAmqpAppender" />
{{- end }}
        </root>
    </log4net>
