dependencies:
  - name: redis
    version: 10.3.2
    condition: redis.enabled
    repository: https://charts.helm.sh/stable
  - name: rabbitmq
    version: 14.5.0
    condition: rabbitmq.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 6.5.0
    condition: postgresql.enabled
    repository: https://charts.helm.sh/stable
  - name: elasticsearch
    version: 7.16.2
    condition: elasticsearch.enabled
    repository: https://helm.elastic.co
