apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-search-service
  labels:
    app: {{ .Release.Name }}-search-service
    chart: {{ template "gs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.searchService.service.type }}
  {{- if (and (eq .Values.searchService.service.type "NodePort") (not (empty .Values.searchService.service.externalTrafficPolicy))) }}
  externalTrafficPolicy: {{ .Values.searchService.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.searchService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.searchService.service.type "NodePort") (not (empty .Values.searchService.service.nodePort))) }}
      nodePort: {{ .Values.searchService.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-search-service
    release: {{ .Release.Name }}
